version: '3.7'

services:
  mongo:
    image: mongo:4.2.1-bionic
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
